import type { KanaMode } from "@/constants/kana";

export interface WordItem {
  id: string;
  romaji: string;
  meaning: string;
  word: string;
  mode: KanaMode;
}

/**
 * Check if a Japanese word can be fully constructed using only the active characters.
 * Handles single kana, Katakana chōonpu (ー), and combo digraphs (ゃ, ゅ, ょ, etc.).
 */
export function canFormWord(word: string, activeChars: Set<string>): boolean {
  let i = 0;
  while (i < word.length) {
    const char = word[i];
    // Katakana long vowel mark 'ー' is permitted in katakana mode
    if (char === "ー") {
      i++;
      continue;
    }

    // Check if next char is a small combo modifier (ゃ, ゅ, ょ, etc.)
    const nextChar = word[i + 1];
    if (nextChar && /[ゃゅょぁぃぅぇぉャュョァィゥェォ]/.test(nextChar)) {
      const combo = char + nextChar;
      if (!activeChars.has(combo)) {
        return false;
      }
      i += 2;
      continue;
    }

    if (!activeChars.has(char)) {
      return false;
    }
    i++;
  }
  return true;
}

/**
 * Split a Japanese word into individual drawing units (combos stay together).
 */
export function getWordCharacters(word: string): string[] {
  const result: string[] = [];
  let i = 0;
  while (i < word.length) {
    const char = word[i];
    const nextChar = word[i + 1];
    if (nextChar && /[ゃゅょぁぃぅぇぉャュョァィゥェォ]/.test(nextChar)) {
      result.push(char + nextChar);
      i += 2;
    } else {
      result.push(char);
      i++;
    }
  }
  return result;
}

export const VOCABULARY_LIST: WordItem[] = [
  // ================= HIRAGANA (JLPT N5 & N4 CORE) =================
  { id: "h_0", word: "あい", romaji: "ai", meaning: "Love", mode: "hiragana" },
  { id: "h_1", word: "いえ", romaji: "ie", meaning: "House", mode: "hiragana" },
  { id: "h_2", word: "うえ", romaji: "ue", meaning: "Above / Top", mode: "hiragana" },
  { id: "h_3", word: "あおい", romaji: "aoi", meaning: "Blue", mode: "hiragana" },
  { id: "h_4", word: "あお", romaji: "ao", meaning: "Blue (Color)", mode: "hiragana" },
  { id: "h_5", word: "いいえ", romaji: "iie", meaning: "No / Not", mode: "hiragana" },
  { id: "h_6", word: "あう", romaji: "au", meaning: "To meet", mode: "hiragana" },
  { id: "h_7", word: "いう", romaji: "iu", meaning: "To speak / say", mode: "hiragana" },
  { id: "h_8", word: "おい", romaji: "oi", meaning: "Nephew", mode: "hiragana" },
  { id: "h_9", word: "え", romaji: "e", meaning: "Picture / Drawing", mode: "hiragana" },
  { id: "h_10", word: "えき", romaji: "eki", meaning: "Station", mode: "hiragana" },
  { id: "h_11", word: "あかい", romaji: "akai", meaning: "Red", mode: "hiragana" },
  { id: "h_12", word: "あか", romaji: "aka", meaning: "Red (Color)", mode: "hiragana" },
  { id: "h_13", word: "かお", romaji: "kao", meaning: "Face", mode: "hiragana" },
  { id: "h_14", word: "きく", romaji: "kiku", meaning: "To listen / Chrysanthemum", mode: "hiragana" },
  { id: "h_15", word: "かき", romaji: "kaki", meaning: "Persimmon", mode: "hiragana" },
  { id: "h_16", word: "いけ", romaji: "ike", meaning: "Pond", mode: "hiragana" },
  { id: "h_17", word: "ここ", romaji: "koko", meaning: "Here", mode: "hiragana" },
  { id: "h_18", word: "き", romaji: "ki", meaning: "Tree", mode: "hiragana" },
  { id: "h_19", word: "かい", romaji: "kai", meaning: "Clam / Shellfish", mode: "hiragana" },
  { id: "h_20", word: "かう", romaji: "kau", meaning: "To buy", mode: "hiragana" },
  { id: "h_21", word: "かく", romaji: "kaku", meaning: "To write", mode: "hiragana" },
  { id: "h_22", word: "いく", romaji: "iku", meaning: "To go", mode: "hiragana" },
  { id: "h_23", word: "こえ", romaji: "koe", meaning: "Voice / Sound", mode: "hiragana" },
  { id: "h_24", word: "おおきい", romaji: "ookii", meaning: "Big / Large", mode: "hiragana" },
  { id: "h_25", word: "おく", romaji: "oku", meaning: "To put / place", mode: "hiragana" },
  { id: "h_26", word: "あく", romaji: "aku", meaning: "To open", mode: "hiragana" },
  { id: "h_27", word: "あさ", romaji: "asa", meaning: "Morning", mode: "hiragana" },
  { id: "h_28", word: "あし", romaji: "ashi", meaning: "Leg / Foot", mode: "hiragana" },
  { id: "h_29", word: "うし", romaji: "ushi", meaning: "Cow", mode: "hiragana" },
  { id: "h_30", word: "いす", romaji: "isu", meaning: "Chair", mode: "hiragana" },
  { id: "h_31", word: "かさ", romaji: "kasa", meaning: "Umbrella", mode: "hiragana" },
  { id: "h_32", word: "さけ", romaji: "sake", meaning: "Sake / Salmon", mode: "hiragana" },
  { id: "h_33", word: "しか", romaji: "shika", meaning: "Deer", mode: "hiragana" },
  { id: "h_34", word: "すし", romaji: "sushi", meaning: "Sushi", mode: "hiragana" },
  { id: "h_35", word: "すいか", romaji: "suika", meaning: "Watermelon", mode: "hiragana" },
  { id: "h_36", word: "おそい", romaji: "osoi", meaning: "Slow / Late", mode: "hiragana" },
  { id: "h_37", word: "そこ", romaji: "soko", meaning: "There", mode: "hiragana" },
  { id: "h_38", word: "すこし", romaji: "sukoshi", meaning: "A little", mode: "hiragana" },
  { id: "h_39", word: "あそこ", romaji: "asoko", meaning: "Over there", mode: "hiragana" },
  { id: "h_40", word: "すう", romaji: "suu", meaning: "To inhale / smoke", mode: "hiragana" },
  { id: "h_41", word: "さく", romaji: "saku", meaning: "To bloom", mode: "hiragana" },
  { id: "h_42", word: "おす", romaji: "osu", meaning: "To push", mode: "hiragana" },
  { id: "h_43", word: "いた", romaji: "ita", meaning: "Board / Plank", mode: "hiragana" },
  { id: "h_44", word: "うた", romaji: "uta", meaning: "Song", mode: "hiragana" },
  { id: "h_45", word: "おと", romaji: "oto", meaning: "Sound", mode: "hiragana" },
  { id: "h_46", word: "て", romaji: "te", meaning: "Hand", mode: "hiragana" },
  { id: "h_47", word: "ちち", romaji: "chichi", meaning: "Father", mode: "hiragana" },
  { id: "h_48", word: "くつ", romaji: "kutsu", meaning: "Shoes", mode: "hiragana" },
  { id: "h_49", word: "つくえ", romaji: "tsukue", meaning: "Desk", mode: "hiragana" },
  { id: "h_50", word: "ちかてつ", romaji: "chikatetsu", meaning: "Subway", mode: "hiragana" },
  { id: "h_51", word: "こと", romaji: "koto", meaning: "Thing / Matter", mode: "hiragana" },
  { id: "h_52", word: "たかい", romaji: "takai", meaning: "Tall / Expensive", mode: "hiragana" },
  { id: "h_53", word: "あつい", romaji: "atsui", meaning: "Hot / Thick", mode: "hiragana" },
  { id: "h_54", word: "いたい", romaji: "itai", meaning: "Painful / Hurt", mode: "hiragana" },
  { id: "h_55", word: "たつ", romaji: "tatsu", meaning: "To stand", mode: "hiragana" },
  { id: "h_56", word: "まつ", romaji: "matsu", meaning: "To wait", mode: "hiragana" },
  { id: "h_57", word: "した", romaji: "shita", meaning: "Below / Under", mode: "hiragana" },
  { id: "h_58", word: "そと", romaji: "soto", meaning: "Outside", mode: "hiragana" },
  { id: "h_59", word: "ちいさい", romaji: "chiisai", meaning: "Small / Little", mode: "hiragana" },
  { id: "h_60", word: "うつくしい", romaji: "utsukushii", meaning: "Beautiful", mode: "hiragana" },
  { id: "h_61", word: "とき", romaji: "toki", meaning: "Time", mode: "hiragana" },
  { id: "h_62", word: "とけい", romaji: "tokei", meaning: "Watch / Clock", mode: "hiragana" },
  { id: "h_63", word: "いぬ", romaji: "inu", meaning: "Dog", mode: "hiragana" },
  { id: "h_64", word: "ねこ", romaji: "neko", meaning: "Cat", mode: "hiragana" },
  { id: "h_65", word: "くに", romaji: "kuni", meaning: "Country", mode: "hiragana" },
  { id: "h_66", word: "なに", romaji: "nani", meaning: "What", mode: "hiragana" },
  { id: "h_67", word: "きのこ", romaji: "kinoko", meaning: "Mushroom", mode: "hiragana" },
  { id: "h_68", word: "さかな", romaji: "sakana", meaning: "Fish", mode: "hiragana" },
  { id: "h_69", word: "おかね", romaji: "okane", meaning: "Money", mode: "hiragana" },
  { id: "h_70", word: "あなた", romaji: "anata", meaning: "You", mode: "hiragana" },
  { id: "h_71", word: "あに", romaji: "ani", meaning: "Older Brother", mode: "hiragana" },
  { id: "h_72", word: "あね", romaji: "ane", meaning: "Older Sister", mode: "hiragana" },
  { id: "h_73", word: "なつ", romaji: "natsu", meaning: "Summer", mode: "hiragana" },
  { id: "h_74", word: "にく", romaji: "niku", meaning: "Meat", mode: "hiragana" },
  { id: "h_75", word: "たいせつ", romaji: "taisetsu", meaning: "Important", mode: "hiragana" },
  { id: "h_76", word: "おとこのこ", romaji: "otokonoko", meaning: "Boy", mode: "hiragana" },
  { id: "h_77", word: "しぬ", romaji: "shinu", meaning: "To die", mode: "hiragana" },
  { id: "h_78", word: "すな", romaji: "suna", meaning: "Sand", mode: "hiragana" },
  { id: "h_79", word: "ひと", romaji: "hito", meaning: "Person", mode: "hiragana" },
  { id: "h_80", word: "はな", romaji: "hana", meaning: "Flower / Nose", mode: "hiragana" },
  { id: "h_81", word: "はし", romaji: "hashi", meaning: "Bridge / Chopsticks", mode: "hiragana" },
  { id: "h_82", word: "ふね", romaji: "fune", meaning: "Boat / Ship", mode: "hiragana" },
  { id: "h_83", word: "ふゆ", romaji: "fuyu", meaning: "Winter", mode: "hiragana" },
  { id: "h_84", word: "ほし", romaji: "hoshi", meaning: "Star", mode: "hiragana" },
  { id: "h_85", word: "ほん", romaji: "hon", meaning: "Book", mode: "hiragana" },
  { id: "h_86", word: "はこ", romaji: "hako", meaning: "Box", mode: "hiragana" },
  { id: "h_87", word: "へや", romaji: "heya", meaning: "Room", mode: "hiragana" },
  { id: "h_88", word: "ひかり", romaji: "hikari", meaning: "Light", mode: "hiragana" },
  { id: "h_89", word: "みみ", romaji: "mimi", meaning: "Ear", mode: "hiragana" },
  { id: "h_90", word: "め", romaji: "me", meaning: "Eye", mode: "hiragana" },
  { id: "h_91", word: "もり", romaji: "mori", meaning: "Forest", mode: "hiragana" },
  { id: "h_92", word: "まち", romaji: "machi", meaning: "City / Town", mode: "hiragana" },
  { id: "h_93", word: "みち", romaji: "michi", meaning: "Street / Path", mode: "hiragana" },
  { id: "h_94", word: "みず", romaji: "mizu", meaning: "Water", mode: "hiragana" },
  { id: "h_95", word: "やま", romaji: "yama", meaning: "Mountain", mode: "hiragana" },
  { id: "h_96", word: "ゆき", romaji: "yuki", meaning: "Snow", mode: "hiragana" },
  { id: "h_97", word: "よる", romaji: "yoru", meaning: "Night", mode: "hiragana" },
  { id: "h_98", word: "ゆめ", romaji: "yume", meaning: "Dream", mode: "hiragana" },
  { id: "h_99", word: "さくら", romaji: "sakura", meaning: "Cherry Blossom", mode: "hiragana" },
  { id: "h_100", word: "とり", romaji: "tori", meaning: "Bird", mode: "hiragana" },
  { id: "h_101", word: "そら", romaji: "sora", meaning: "Sky", mode: "hiragana" },
  { id: "h_102", word: "はる", romaji: "haru", meaning: "Spring", mode: "hiragana" },
  { id: "h_103", word: "かわ", romaji: "kawa", meaning: "River", mode: "hiragana" },
  { id: "h_104", word: "わたし", romaji: "watashi", meaning: "I / Me", mode: "hiragana" },
  { id: "h_105", word: "くるま", romaji: "kuruma", meaning: "Car", mode: "hiragana" },
  { id: "h_106", word: "せんせい", romaji: "sensei", meaning: "Teacher / Doctor", mode: "hiragana" },
  { id: "h_107", word: "がくせい", romaji: "gakusei", meaning: "Student", mode: "hiragana" },
  { id: "h_108", word: "ともだち", romaji: "tomodachi", meaning: "Friend", mode: "hiragana" },
  { id: "h_109", word: "かぞく", romaji: "kazoku", meaning: "Family", mode: "hiragana" },
  { id: "h_110", word: "にほん", romaji: "nihon", meaning: "Japan", mode: "hiragana" },
  { id: "h_111", word: "ありがとう", romaji: "arigatou", meaning: "Thank you", mode: "hiragana" },
  { id: "h_112", word: "おはよう", romaji: "ohayou", meaning: "Good morning", mode: "hiragana" },
  { id: "h_113", word: "こんばんは", romaji: "konbanwa", meaning: "Good evening", mode: "hiragana" },
  { id: "h_114", word: "さようなら", romaji: "sayounara", meaning: "Goodbye", mode: "hiragana" },
  { id: "h_115", word: "きょう", romaji: "kyou", meaning: "Today", mode: "hiragana" },
  { id: "h_116", word: "あした", romaji: "ashita", meaning: "Tomorrow", mode: "hiragana" },
  { id: "h_117", word: "きのう", romaji: "kinou", meaning: "Yesterday", mode: "hiragana" },
  { id: "h_118", word: "まいあさ", romaji: "maiasa", meaning: "Every morning", mode: "hiragana" },
  { id: "h_119", word: "まいばん", romaji: "maiban", meaning: "Every evening", mode: "hiragana" },
  { id: "h_120", word: "まいにち", romaji: "mainichi", meaning: "Every day", mode: "hiragana" },
  { id: "h_121", word: "あめ", romaji: "ame", meaning: "Rain / Candy", mode: "hiragana" },
  { id: "h_122", word: "おちゃ", romaji: "ocha", meaning: "Green Tea", mode: "hiragana" },
  { id: "h_123", word: "みかん", romaji: "mikan", meaning: "Mandarin Orange", mode: "hiragana" },
  { id: "h_124", word: "りんご", romaji: "ringo", meaning: "Apple", mode: "hiragana" },
  { id: "h_125", word: "たまご", romaji: "tamago", meaning: "Egg", mode: "hiragana" },
  { id: "h_126", word: "ごはん", romaji: "gohan", meaning: "Rice / Meal", mode: "hiragana" },
  { id: "h_127", word: "あさごはん", romaji: "asagohan", meaning: "Breakfast", mode: "hiragana" },
  { id: "h_128", word: "ひるごはん", romaji: "hirugohan", meaning: "Lunch", mode: "hiragana" },
  { id: "h_129", word: "ばんごはん", romaji: "bangohan", meaning: "Dinner", mode: "hiragana" },
  { id: "h_130", word: "みせ", romaji: "mise", meaning: "Store / Shop", mode: "hiragana" },
  { id: "h_131", word: "ぎんこう", romaji: "ginkou", meaning: "Bank", mode: "hiragana" },
  { id: "h_132", word: "びょういん", romaji: "byouin", meaning: "Hospital", mode: "hiragana" },
  { id: "h_133", word: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "Post Office", mode: "hiragana" },
  { id: "h_134", word: "としょかん", romaji: "toshokan", meaning: "Library", mode: "hiragana" },
  { id: "h_135", word: "えいがかん", romaji: "eigakan", meaning: "Movie Theater", mode: "hiragana" },
  { id: "h_136", word: "がっこう", romaji: "gakkou", meaning: "School", mode: "hiragana" },
  { id: "h_137", word: "だいがく", romaji: "daigaku", meaning: "University", mode: "hiragana" },
  { id: "h_138", word: "かいしゃ", romaji: "kaisha", meaning: "Company / Office", mode: "hiragana" },
  { id: "h_139", word: "ひこうき", romaji: "hikouki", meaning: "Airplane", mode: "hiragana" },
  { id: "h_140", word: "じてんしゃ", romaji: "jitensha", meaning: "Bicycle", mode: "hiragana" },
  { id: "h_141", word: "しんかんせん", romaji: "shinkansen", meaning: "Bullet Train (Shinkansen)", mode: "hiragana" },
  { id: "h_142", word: "あるく", romaji: "aruku", meaning: "To walk", mode: "hiragana" },
  { id: "h_143", word: "はしる", romaji: "hashiru", meaning: "To run", mode: "hiragana" },
  { id: "h_144", word: "およぐ", romaji: "oyogu", meaning: "To swim", mode: "hiragana" },
  { id: "h_145", word: "のむ", romaji: "nomu", meaning: "To drink", mode: "hiragana" },
  { id: "h_146", word: "たべる", romaji: "taberu", meaning: "To eat", mode: "hiragana" },
  { id: "h_147", word: "みる", romaji: "miru", meaning: "To see / watch", mode: "hiragana" },
  { id: "h_148", word: "よむ", romaji: "yomu", meaning: "To read", mode: "hiragana" },
  { id: "h_149", word: "とる", romaji: "toru", meaning: "To take / photograph", mode: "hiragana" },
  { id: "h_150", word: "する", romaji: "suru", meaning: "To do", mode: "hiragana" },
  { id: "h_151", word: "くる", romaji: "kuru", meaning: "To come", mode: "hiragana" },
  { id: "h_152", word: "かえる", romaji: "kaeru", meaning: "To go home / return", mode: "hiragana" },
  { id: "h_153", word: "ねる", romaji: "neru", meaning: "To sleep", mode: "hiragana" },
  { id: "h_154", word: "おきる", romaji: "okiru", meaning: "To wake up", mode: "hiragana" },
  { id: "h_155", word: "べんきょう", romaji: "benkyou", meaning: "To study", mode: "hiragana" },
  { id: "h_156", word: "しごと", romaji: "shigoto", meaning: "Job / Work", mode: "hiragana" },
  { id: "h_157", word: "りょこう", romaji: "ryokou", meaning: "Travel / Trip", mode: "hiragana" },
  { id: "h_158", word: "かいもの", romaji: "kaimono", meaning: "Shopping", mode: "hiragana" },
  { id: "h_159", word: "さんぽ", romaji: "sanpo", meaning: "Stroll / Walk", mode: "hiragana" },
  { id: "h_160", word: "うたう", romaji: "utau", meaning: "To sing", mode: "hiragana" },
  { id: "h_161", word: "あそぶ", romaji: "asobu", meaning: "To play", mode: "hiragana" },
  { id: "h_162", word: "はなす", romaji: "hanasu", meaning: "To talk / speak", mode: "hiragana" },
  { id: "h_163", word: "わかる", romaji: "wakaru", meaning: "To understand", mode: "hiragana" },
  { id: "h_164", word: "しる", romaji: "shiru", meaning: "To know", mode: "hiragana" },
  { id: "h_165", word: "おもう", romaji: "omou", meaning: "To think", mode: "hiragana" },
  { id: "h_166", word: "よぶ", romaji: "yobu", meaning: "To call", mode: "hiragana" },
  { id: "h_167", word: "おしえる", romaji: "oshieru", meaning: "To teach / tell", mode: "hiragana" },
  { id: "h_168", word: "ならう", romaji: "narau", meaning: "To learn", mode: "hiragana" },
  { id: "h_169", word: "てつだう", romaji: "tetsudau", meaning: "To help", mode: "hiragana" },
  { id: "h_170", word: "あける", romaji: "akeru", meaning: "To open", mode: "hiragana" },
  { id: "h_171", word: "しめる", romaji: "shimeru", meaning: "To close", mode: "hiragana" },
  { id: "h_172", word: "つける", romaji: "tsukeru", meaning: "To turn on", mode: "hiragana" },
  { id: "h_173", word: "けす", romaji: "kesu", meaning: "To turn off / erase", mode: "hiragana" },
  { id: "h_174", word: "いれる", romaji: "ireru", meaning: "To insert / put in", mode: "hiragana" },
  { id: "h_175", word: "だす", romaji: "dasu", meaning: "To take out / hand over", mode: "hiragana" },
  { id: "h_176", word: "もつ", romaji: "motsu", meaning: "To hold / have", mode: "hiragana" },
  { id: "h_177", word: "すむ", romaji: "sumu", meaning: "To live / reside", mode: "hiragana" },
  { id: "h_178", word: "すわる", romaji: "suwaru", meaning: "To sit", mode: "hiragana" },
  { id: "h_179", word: "はいる", romaji: "hairu", meaning: "To enter", mode: "hiragana" },
  { id: "h_180", word: "でる", romaji: "deru", meaning: "To exit", mode: "hiragana" },
  { id: "h_181", word: "わたる", romaji: "wataru", meaning: "To cross", mode: "hiragana" },
  { id: "h_182", word: "まがる", romaji: "magaru", meaning: "To turn", mode: "hiragana" },
  { id: "h_183", word: "とまる", romaji: "tomaru", meaning: "To stop / stay", mode: "hiragana" },
  { id: "h_184", word: "くもり", romaji: "kumori", meaning: "Cloudy", mode: "hiragana" },
  { id: "h_185", word: "はれ", romaji: "hare", meaning: "Sunny / Clear", mode: "hiragana" },
  { id: "h_186", word: "かぜ", romaji: "kaze", meaning: "Wind / Cold", mode: "hiragana" },
  { id: "h_187", word: "おんがく", romaji: "ongaku", meaning: "Music", mode: "hiragana" },
  { id: "h_188", word: "しゃしん", romaji: "shashin", meaning: "Photo", mode: "hiragana" },
  { id: "h_189", word: "てがみ", romaji: "tegami", meaning: "Letter", mode: "hiragana" },
  { id: "h_190", word: "きっぷ", romaji: "kippu", meaning: "Ticket", mode: "hiragana" },
  { id: "h_191", word: "さいふ", romaji: "saifu", meaning: "Wallet", mode: "hiragana" },
  { id: "h_192", word: "かばん", romaji: "kaban", meaning: "Bag", mode: "hiragana" },
  { id: "h_193", word: "ぼうし", romaji: "boushi", meaning: "Hat", mode: "hiragana" },
  { id: "h_194", word: "めがね", romaji: "megane", meaning: "Glasses", mode: "hiragana" },
  { id: "h_195", word: "ふく", romaji: "fuku", meaning: "Clothes", mode: "hiragana" },
  { id: "h_196", word: "くつした", romaji: "kutsushita", meaning: "Socks", mode: "hiragana" },
  { id: "h_197", word: "かぎ", romaji: "kagi", meaning: "Key", mode: "hiragana" },
  { id: "h_198", word: "かみ", romaji: "kami", meaning: "Paper / Hair / God", mode: "hiragana" },
  { id: "h_199", word: "てちょう", romaji: "techou", meaning: "Pocket Notebook", mode: "hiragana" },
  { id: "h_200", word: "じしょ", romaji: "jisho", meaning: "Dictionary", mode: "hiragana" },
  { id: "h_201", word: "ざっし", romaji: "zasshi", meaning: "Magazine", mode: "hiragana" },
  { id: "h_202", word: "しんぶん", romaji: "shinbun", meaning: "Newspaper", mode: "hiragana" },
  { id: "h_203", word: "えんぴつ", romaji: "enpitsu", meaning: "Pencil", mode: "hiragana" },
  { id: "h_204", word: "けしごむ", romaji: "keshigomu", meaning: "Eraser", mode: "hiragana" },
  { id: "h_205", word: "でんわ", romaji: "denwa", meaning: "Telephone", mode: "hiragana" },
  { id: "h_206", word: "まど", romaji: "mado", meaning: "Window", mode: "hiragana" },
  { id: "h_207", word: "だいどころ", romaji: "daidokoro", meaning: "Kitchen", mode: "hiragana" },
  { id: "h_208", word: "おふろ", romaji: "ofuro", meaning: "Japanese Bath (Ofuro)", mode: "hiragana" },
  { id: "h_209", word: "にわ", romaji: "niwa", meaning: "Garden / Yard", mode: "hiragana" },
  { id: "h_210", word: "げんかん", romaji: "genkan", meaning: "Entrance Hall (Genkan)", mode: "hiragana" },
  { id: "h_211", word: "かいだん", romaji: "kaidan", meaning: "Stairs", mode: "hiragana" },
  { id: "h_212", word: "ろうか", romaji: "rouka", meaning: "Hallway", mode: "hiragana" },
  { id: "h_213", word: "たてもの", romaji: "tatemono", meaning: "Building", mode: "hiragana" },
  { id: "h_214", word: "こうえん", romaji: "kouen", meaning: "City Park", mode: "hiragana" },
  { id: "h_215", word: "うみ", romaji: "umi", meaning: "Sea / Ocean", mode: "hiragana" },
  { id: "h_216", word: "しま", romaji: "shima", meaning: "Island", mode: "hiragana" },
  { id: "h_217", word: "つき", romaji: "tsuki", meaning: "Moon", mode: "hiragana" },
  { id: "h_218", word: "たいよう", romaji: "taiyou", meaning: "Sun", mode: "hiragana" },
  { id: "h_219", word: "ひる", romaji: "hiru", meaning: "Daytime", mode: "hiragana" },
  { id: "h_220", word: "ゆうがた", romaji: "yuugata", meaning: "Evening", mode: "hiragana" },
  { id: "h_221", word: "いま", romaji: "ima", meaning: "Now", mode: "hiragana" },
  { id: "h_222", word: "ごぜん", romaji: "gozen", meaning: "Pagi (A.M.)", mode: "hiragana" },
  { id: "h_223", word: "ごご", romaji: "gogo", meaning: "Sore / Malam (P.M.)", mode: "hiragana" },
  { id: "h_224", word: "なんじ", romaji: "nanji", meaning: "What time", mode: "hiragana" },
  { id: "h_225", word: "なんぷん", romaji: "nanpun", meaning: "What minute", mode: "hiragana" },
  { id: "h_226", word: "あさって", romaji: "asatte", meaning: "Day after tomorrow", mode: "hiragana" },
  { id: "h_227", word: "おととい", romaji: "ototoi", meaning: "Day before yesterday", mode: "hiragana" },
  { id: "h_228", word: "こんしゅう", romaji: "konshuu", meaning: "This week", mode: "hiragana" },
  { id: "h_229", word: "らいしゅう", romaji: "raishuu", meaning: "Next week", mode: "hiragana" },
  { id: "h_230", word: "せんしゅう", romaji: "senshuu", meaning: "Last week", mode: "hiragana" },
  { id: "h_231", word: "こんげつ", romaji: "kongetsu", meaning: "This month", mode: "hiragana" },
  { id: "h_232", word: "らいげつ", romaji: "raigetsu", meaning: "Next month", mode: "hiragana" },
  { id: "h_233", word: "せんげつ", romaji: "sengetsu", meaning: "Last month", mode: "hiragana" },
  { id: "h_234", word: "ことし", romaji: "kotoshi", meaning: "This year", mode: "hiragana" },
  { id: "h_235", word: "らいねん", romaji: "rainen", meaning: "Next year", mode: "hiragana" },
  { id: "h_236", word: "きょねん", romaji: "kyonen", meaning: "Last year", mode: "hiragana" },
  { id: "h_237", word: "げつようび", romaji: "getsuyoubi", meaning: "Monday", mode: "hiragana" },
  { id: "h_238", word: "かようび", romaji: "kayoubi", meaning: "Tuesday", mode: "hiragana" },
  { id: "h_239", word: "すいようび", romaji: "suiyoubi", meaning: "Wednesday", mode: "hiragana" },
  { id: "h_240", word: "もくようび", romaji: "mokuyoubi", meaning: "Thursday", mode: "hiragana" },
  { id: "h_241", word: "きんようび", romaji: "kinyoubi", meaning: "Friday", mode: "hiragana" },
  { id: "h_242", word: "どようび", romaji: "doyoubi", meaning: "Saturday", mode: "hiragana" },
  { id: "h_243", word: "にちようび", romaji: "nichiyoubi", meaning: "Sunday", mode: "hiragana" },
  { id: "h_244", word: "あたま", romaji: "atama", meaning: "Head", mode: "hiragana" },
  { id: "h_245", word: "くち", romaji: "kuchi", meaning: "Mouth", mode: "hiragana" },
  { id: "h_246", word: "からだ", romaji: "karada", meaning: "Body", mode: "hiragana" },
  { id: "h_247", word: "おなか", romaji: "onaka", meaning: "Stomach", mode: "hiragana" },
  { id: "h_248", word: "せなか", romaji: "senaka", meaning: "Back", mode: "hiragana" },
  { id: "h_249", word: "むね", romaji: "mune", meaning: "Chest", mode: "hiragana" },
  { id: "h_250", word: "のど", romaji: "nodo", meaning: "Throat", mode: "hiragana" },
  { id: "h_251", word: "おとうさん", romaji: "otousan", meaning: "Ayah (formal)", mode: "hiragana" },
  { id: "h_252", word: "おかあさん", romaji: "okaasan", meaning: "Ibu (formal)", mode: "hiragana" },
  { id: "h_253", word: "おにいさん", romaji: "oniisan", meaning: "Older Brother", mode: "hiragana" },
  { id: "h_254", word: "おねえさん", romaji: "oneesan", meaning: "Older Sister", mode: "hiragana" },
  { id: "h_255", word: "おとうと", romaji: "otouto", meaning: "Younger Brother", mode: "hiragana" },
  { id: "h_256", word: "いもうと", romaji: "imouto", meaning: "Younger Sister", mode: "hiragana" },
  { id: "h_257", word: "おっと", romaji: "otto", meaning: "Husband", mode: "hiragana" },
  { id: "h_258", word: "つま", romaji: "tsuma", meaning: "Wife", mode: "hiragana" },
  { id: "h_259", word: "おとこのひと", romaji: "otokonohito", meaning: "Adult Man", mode: "hiragana" },
  { id: "h_260", word: "おんなのひと", romaji: "onnanohito", meaning: "Adult Woman", mode: "hiragana" },
  { id: "h_261", word: "おんなのこ", romaji: "onnanoko", meaning: "Girl", mode: "hiragana" },
  { id: "h_262", word: "あかちゃん", romaji: "akachan", meaning: "Baby", mode: "hiragana" },
  { id: "h_263", word: "おとな", romaji: "otona", meaning: "Adult", mode: "hiragana" },
  { id: "h_264", word: "せいと", romaji: "seito", meaning: "School Pupil", mode: "hiragana" },
  { id: "h_265", word: "りゅうがくせい", romaji: "ryuugakusei", meaning: "International Student", mode: "hiragana" },
  { id: "h_266", word: "いしゃ", romaji: "isha", meaning: "Doctor", mode: "hiragana" },
  { id: "h_267", word: "かんごし", romaji: "kangoshi", meaning: "Nurse", mode: "hiragana" },
  { id: "h_268", word: "けいさつかん", romaji: "keisatsukan", meaning: "Police Officer", mode: "hiragana" },
  { id: "h_269", word: "てんいん", romaji: "ten'in", meaning: "Store Clerk", mode: "hiragana" },
  { id: "h_270", word: "ぎんこういん", romaji: "ginkouin", meaning: "Bank Clerk", mode: "hiragana" },
  { id: "h_271", word: "かいしゃいん", romaji: "kaishain", meaning: "Company Employee", mode: "hiragana" },

  // ================= KATAKANA (GAIRAIGO LOANWORDS) =================
  { id: "k_0", word: "アイス", romaji: "aisu", meaning: "Ice Cream", mode: "katakana" },
  { id: "k_1", word: "アイスクリーム", romaji: "aisukuriimu", meaning: "Ice Cream", mode: "katakana" },
  { id: "k_2", word: "アイドル", romaji: "aidoru", meaning: "Idol", mode: "katakana" },
  { id: "k_3", word: "アイデア", romaji: "aidea", meaning: "Idea", mode: "katakana" },
  { id: "k_4", word: "アニメ", romaji: "anime", meaning: "Anime / Animation", mode: "katakana" },
  { id: "k_5", word: "アパート", romaji: "apaato", meaning: "Apartment", mode: "katakana" },
  { id: "k_6", word: "アプリ", romaji: "apuri", meaning: "App / Application", mode: "katakana" },
  { id: "k_7", word: "アルバイト", romaji: "arubaito", meaning: "Part-time Job", mode: "katakana" },
  { id: "k_8", word: "アルバム", romaji: "arubamu", meaning: "Album", mode: "katakana" },
  { id: "k_9", word: "インターネット", romaji: "intaanetto", meaning: "Internet", mode: "katakana" },
  { id: "k_10", word: "イラスト", romaji: "irasuto", meaning: "Illustration", mode: "katakana" },
  { id: "k_11", word: "エアコン", romaji: "eakon", meaning: "Air Conditioner", mode: "katakana" },
  { id: "k_12", word: "エスカレーター", romaji: "esukareetaa", meaning: "Escalator", mode: "katakana" },
  { id: "k_13", word: "エレベーター", romaji: "erebeetaa", meaning: "Elevator", mode: "katakana" },
  { id: "k_14", word: "エネルギー", romaji: "enerugii", meaning: "Energy", mode: "katakana" },
  { id: "k_15", word: "カーテン", romaji: "kaaten", meaning: "Curtain", mode: "katakana" },
  { id: "k_16", word: "カード", romaji: "kaado", meaning: "Card", mode: "katakana" },
  { id: "k_17", word: "カレー", romaji: "karee", meaning: "Curry Rice", mode: "katakana" },
  { id: "k_18", word: "カメラ", romaji: "kamera", meaning: "Camera", mode: "katakana" },
  { id: "k_19", word: "カップ", romaji: "kappu", meaning: "Cup", mode: "katakana" },
  { id: "k_20", word: "カレンダー", romaji: "karendaa", meaning: "Calendar", mode: "katakana" },
  { id: "k_21", word: "ギター", romaji: "gitaa", meaning: "Guitar", mode: "katakana" },
  { id: "k_22", word: "グラス", romaji: "gurasu", meaning: "Glass", mode: "katakana" },
  { id: "k_23", word: "クラス", romaji: "kurasu", meaning: "Class", mode: "katakana" },
  { id: "k_24", word: "クラブ", romaji: "kurabu", meaning: "Club", mode: "katakana" },
  { id: "k_25", word: "クリスマス", romaji: "kurisumasu", meaning: "Christmas", mode: "katakana" },
  { id: "k_26", word: "ケーキ", romaji: "keeki", meaning: "Cake", mode: "katakana" },
  { id: "k_27", word: "ゲーム", romaji: "geemu", meaning: "Game", mode: "katakana" },
  { id: "k_28", word: "コーヒー", romaji: "koohii", meaning: "Coffee", mode: "katakana" },
  { id: "k_29", word: "コート", romaji: "kooto", meaning: "Winter Coat", mode: "katakana" },
  { id: "k_30", word: "コピー", romaji: "kopii", meaning: "Photocopy", mode: "katakana" },
  { id: "k_31", word: "コンサート", romaji: "konsaato", meaning: "Concert", mode: "katakana" },
  { id: "k_32", word: "コンピューター", romaji: "konpyuutaa", meaning: "Computer", mode: "katakana" },
  { id: "k_33", word: "コンビニ", romaji: "konbini", meaning: "Convenience Store", mode: "katakana" },
  { id: "k_34", word: "サラダ", romaji: "sarada", meaning: "Salad", mode: "katakana" },
  { id: "k_35", word: "サンダル", romaji: "sandaru", meaning: "Sandals", mode: "katakana" },
  { id: "k_36", word: "サンドイッチ", romaji: "sandoicchi", meaning: "Sandwich", mode: "katakana" },
  { id: "k_37", word: "サービス", romaji: "saabisu", meaning: "Service", mode: "katakana" },
  { id: "k_38", word: "シャツ", romaji: "shatsu", meaning: "Shirt", mode: "katakana" },
  { id: "k_39", word: "シャワー", romaji: "shawaa", meaning: "Shower", mode: "katakana" },
  { id: "k_40", word: "ジュース", romaji: "juusu", meaning: "Juice", mode: "katakana" },
  { id: "k_41", word: "スカート", romaji: "sukaato", meaning: "Skirt", mode: "katakana" },
  { id: "k_42", word: "スキー", romaji: "sukii", meaning: "Ski", mode: "katakana" },
  { id: "k_43", word: "スプーン", romaji: "supuun", meaning: "Spoon", mode: "katakana" },
  { id: "k_44", word: "スポーツ", romaji: "supootsu", meaning: "Sports", mode: "katakana" },
  { id: "k_45", word: "ズボン", romaji: "zubon", meaning: "Pants / Trousers", mode: "katakana" },
  { id: "k_46", word: "スマホ", romaji: "sumaho", meaning: "Smartphone", mode: "katakana" },
  { id: "k_47", word: "スーパー", romaji: "suupaa", meaning: "Supermarket", mode: "katakana" },
  { id: "k_48", word: "スーツ", romaji: "suutsu", meaning: "Suit", mode: "katakana" },
  { id: "k_49", word: "スーツケース", romaji: "suutsukeesu", meaning: "Suitcase", mode: "katakana" },
  { id: "k_50", word: "ステレオ", romaji: "sutereo", meaning: "Stereo", mode: "katakana" },
  { id: "k_51", word: "ストロー", romaji: "sutoroo", meaning: "Straw", mode: "katakana" },
  { id: "k_52", word: "セーター", romaji: "seetaa", meaning: "Sweater", mode: "katakana" },
  { id: "k_53", word: "ソファ", romaji: "sofa", meaning: "Sofa", mode: "katakana" },
  { id: "k_54", word: "タクシー", romaji: "takushii", meaning: "Taxi", mode: "katakana" },
  { id: "k_55", word: "タオル", romaji: "taoru", meaning: "Towel", mode: "katakana" },
  { id: "k_56", word: "タイプ", romaji: "taipu", meaning: "Type", mode: "katakana" },
  { id: "k_57", word: "チーズ", romaji: "chiizu", meaning: "Cheese", mode: "katakana" },
  { id: "k_58", word: "チケット", romaji: "chiketto", meaning: "Ticket", mode: "katakana" },
  { id: "k_59", word: "チョコレート", romaji: "chokoreeto", meaning: "Chocolate", mode: "katakana" },
  { id: "k_60", word: "テーブル", romaji: "teeburu", meaning: "Table", mode: "katakana" },
  { id: "k_61", word: "テープ", romaji: "teepu", meaning: "Tape", mode: "katakana" },
  { id: "k_62", word: "テレビ", romaji: "terebi", meaning: "Television", mode: "katakana" },
  { id: "k_63", word: "テスト", romaji: "tesuto", meaning: "Test / Exam", mode: "katakana" },
  { id: "k_64", word: "テニス", romaji: "tenisu", meaning: "Tennis", mode: "katakana" },
  { id: "k_65", word: "トイレ", romaji: "toire", meaning: "Toilet / Restroom", mode: "katakana" },
  { id: "k_66", word: "トースト", romaji: "toosuto", meaning: "Toast", mode: "katakana" },
  { id: "k_67", word: "トマト", romaji: "tomato", meaning: "Tomato", mode: "katakana" },
  { id: "k_68", word: "ドア", romaji: "doa", meaning: "Door", mode: "katakana" },
  { id: "k_69", word: "ドラマ", romaji: "dorama", meaning: "Drama", mode: "katakana" },
  { id: "k_70", word: "ドレス", romaji: "doresu", meaning: "Dress", mode: "katakana" },
  { id: "k_71", word: "ナイフ", romaji: "naifu", meaning: "Knife", mode: "katakana" },
  { id: "k_72", word: "ニュース", romaji: "nyuusu", meaning: "TV News", mode: "katakana" },
  { id: "k_73", word: "ネクタイ", romaji: "nekutai", meaning: "Necktie", mode: "katakana" },
  { id: "k_74", word: "ノート", romaji: "nooto", meaning: "Notebook", mode: "katakana" },
  { id: "k_75", word: "パーティー", romaji: "paatii", meaning: "Party", mode: "katakana" },
  { id: "k_76", word: "パソコン", romaji: "pasokon", meaning: "PC / Laptop", mode: "katakana" },
  { id: "k_77", word: "バス", romaji: "basu", meaning: "Bus", mode: "katakana" },
  { id: "k_78", word: "バター", romaji: "bataa", meaning: "Butter", mode: "katakana" },
  { id: "k_79", word: "バナナ", romaji: "banana", meaning: "Banana", mode: "katakana" },
  { id: "k_80", word: "パン", romaji: "pan", meaning: "Bread", mode: "katakana" },
  { id: "k_81", word: "ピアノ", romaji: "piano", meaning: "Piano", mode: "katakana" },
  { id: "k_82", word: "ビデオ", romaji: "bideo", meaning: "Video", mode: "katakana" },
  { id: "k_83", word: "ビル", romaji: "biru", meaning: "Building", mode: "katakana" },
  { id: "k_84", word: "プール", romaji: "puuru", meaning: "Swimming Pool", mode: "katakana" },
  { id: "k_85", word: "フォーク", romaji: "fooku", meaning: "Fork", mode: "katakana" },
  { id: "k_86", word: "ベッド", romaji: "beddo", meaning: "Bed", mode: "katakana" },
  { id: "k_87", word: "ペット", romaji: "petto", meaning: "Pet", mode: "katakana" },
  { id: "k_88", word: "ペン", romaji: "pen", meaning: "Pen", mode: "katakana" },
  { id: "k_89", word: "ボール", romaji: "booru", meaning: "Ball", mode: "katakana" },
  { id: "k_90", word: "ボールペン", romaji: "boorupen", meaning: "Ballpoint Pen", mode: "katakana" },
  { id: "k_91", word: "ポケット", romaji: "poketto", meaning: "Pocket", mode: "katakana" },
  { id: "k_92", word: "ポスト", romaji: "posuto", meaning: "Postbox", mode: "katakana" },
  { id: "k_93", word: "ボタン", romaji: "botan", meaning: "Button", mode: "katakana" },
  { id: "k_94", word: "ホテル", romaji: "hoteru", meaning: "Hotel", mode: "katakana" },
  { id: "k_95", word: "マフラー", romaji: "mafuraa", meaning: "Scarf / Muffler", mode: "katakana" },
  { id: "k_96", word: "マンション", romaji: "manshon", meaning: "Condo / Mansion", mode: "katakana" },
  { id: "k_97", word: "ミルク", romaji: "miruku", meaning: "Milk", mode: "katakana" },
  { id: "k_98", word: "メニュー", romaji: "menyuu", meaning: "Menu", mode: "katakana" },
  { id: "k_99", word: "メンバー", romaji: "membaa", meaning: "Member", mode: "katakana" },
  { id: "k_100", word: "ラジオ", romaji: "rajio", meaning: "Radio", mode: "katakana" },
  { id: "k_101", word: "ランチ", romaji: "ranchi", meaning: "Lunch", mode: "katakana" },
  { id: "k_102", word: "レストラン", romaji: "resutoran", meaning: "Restaurant", mode: "katakana" },
  { id: "k_103", word: "ワイシャツ", romaji: "waishatsu", meaning: "White Dress Shirt", mode: "katakana" },
];
