import type { KanaMode } from "@/constants/kana";

export interface WordItem {
  id: string;
  romaji: string;
  meaning: string;
  word: string;
  mode: KanaMode;
}

/**
 * Check if a Japanese word can be fully constructed using only the active characters.
 * Handles single kana, Katakana chōonpu (ー), and combo digraphs (ゃ, ゅ, ょ, etc.).
 */
export function canFormWord(word: string, activeChars: Set<string>): boolean {
  let i = 0;
  while (i < word.length) {
    const char = word[i];
    // Katakana long vowel mark 'ー' is permitted in katakana mode
    if (char === "ー") {
      i++;
      continue;
    }

    // Check if next char is a small combo modifier (ゃ, ゅ, ょ, etc.)
    const nextChar = word[i + 1];
    if (nextChar && /[ゃゅょぁぃぅぇぉャュョァィゥェォ]/.test(nextChar)) {
      const combo = char + nextChar;
      if (!activeChars.has(combo)) {
        return false;
      }
      i += 2;
      continue;
    }

    if (!activeChars.has(char)) {
      return false;
    }
    i++;
  }
  return true;
}

/**
 * Split a Japanese word into individual drawing units (combos stay together).
 */
export function getWordCharacters(word: string): string[] {
  const result: string[] = [];
  let i = 0;
  while (i < word.length) {
    const char = word[i];
    const nextChar = word[i + 1];
    if (nextChar && /[ゃゅょぁぃぅぇぉャュョァィゥェォ]/.test(nextChar)) {
      result.push(char + nextChar);
      i += 2;
    } else {
      result.push(char);
      i++;
    }
  }
  return result;
}

export const VOCABULARY_LIST: WordItem[] = [
  // ================= HIRAGANA (JLPT N5 & N4 CORE) =================
  { id: "h_0", word: "あい", romaji: "ai", meaning: "Cinta / Kasih", mode: "hiragana" },
  { id: "h_1", word: "いえ", romaji: "ie", meaning: "Rumah", mode: "hiragana" },
  { id: "h_2", word: "うえ", romaji: "ue", meaning: "Atas", mode: "hiragana" },
  { id: "h_3", word: "あおい", romaji: "aoi", meaning: "Biru", mode: "hiragana" },
  { id: "h_4", word: "あお", romaji: "ao", meaning: "Warna Biru", mode: "hiragana" },
  { id: "h_5", word: "いいえ", romaji: "iie", meaning: "Tidak / Bukan", mode: "hiragana" },
  { id: "h_6", word: "あう", romaji: "au", meaning: "Bertemu", mode: "hiragana" },
  { id: "h_7", word: "いう", romaji: "iu", meaning: "Berkata / Bicara", mode: "hiragana" },
  { id: "h_8", word: "おい", romaji: "oi", meaning: "Keponakan laki-laki", mode: "hiragana" },
  { id: "h_9", word: "え", romaji: "e", meaning: "Gambar / Lukisan", mode: "hiragana" },
  { id: "h_10", word: "えき", romaji: "eki", meaning: "Stasiun", mode: "hiragana" },
  { id: "h_11", word: "あかい", romaji: "akai", meaning: "Merah", mode: "hiragana" },
  { id: "h_12", word: "あか", romaji: "aka", meaning: "Warna Merah", mode: "hiragana" },
  { id: "h_13", word: "かお", romaji: "kao", meaning: "Wajah", mode: "hiragana" },
  { id: "h_14", word: "きく", romaji: "kiku", meaning: "Mendengar / Bunga Krisan", mode: "hiragana" },
  { id: "h_15", word: "かき", romaji: "kaki", meaning: "Kesemek", mode: "hiragana" },
  { id: "h_16", word: "いけ", romaji: "ike", meaning: "Kolam", mode: "hiragana" },
  { id: "h_17", word: "ここ", romaji: "koko", meaning: "Di sini", mode: "hiragana" },
  { id: "h_18", word: "き", romaji: "ki", meaning: "Pohon", mode: "hiragana" },
  { id: "h_19", word: "かい", romaji: "kai", meaning: "Kerang", mode: "hiragana" },
  { id: "h_20", word: "かう", romaji: "kau", meaning: "Membeli", mode: "hiragana" },
  { id: "h_21", word: "かく", romaji: "kaku", meaning: "Menulis", mode: "hiragana" },
  { id: "h_22", word: "いく", romaji: "iku", meaning: "Pergi", mode: "hiragana" },
  { id: "h_23", word: "こえ", romaji: "koe", meaning: "Suara", mode: "hiragana" },
  { id: "h_24", word: "おおきい", romaji: "ookii", meaning: "Besar", mode: "hiragana" },
  { id: "h_25", word: "おく", romaji: "oku", meaning: "Menaruh", mode: "hiragana" },
  { id: "h_26", word: "あく", romaji: "aku", meaning: "Terbuka", mode: "hiragana" },
  { id: "h_27", word: "あさ", romaji: "asa", meaning: "Pagi", mode: "hiragana" },
  { id: "h_28", word: "あし", romaji: "ashi", meaning: "Kaki", mode: "hiragana" },
  { id: "h_29", word: "うし", romaji: "ushi", meaning: "Sapi", mode: "hiragana" },
  { id: "h_30", word: "いす", romaji: "isu", meaning: "Kursi", mode: "hiragana" },
  { id: "h_31", word: "かさ", romaji: "kasa", meaning: "Payung", mode: "hiragana" },
  { id: "h_32", word: "さけ", romaji: "sake", meaning: "Minuman Sake / Ikan Salmon", mode: "hiragana" },
  { id: "h_33", word: "しか", romaji: "shika", meaning: "Rusa", mode: "hiragana" },
  { id: "h_34", word: "すし", romaji: "sushi", meaning: "Sushi", mode: "hiragana" },
  { id: "h_35", word: "すいか", romaji: "suika", meaning: "Semangka", mode: "hiragana" },
  { id: "h_36", word: "おそい", romaji: "osoi", meaning: "Lambat / Terlambat", mode: "hiragana" },
  { id: "h_37", word: "そこ", romaji: "soko", meaning: "Di sana", mode: "hiragana" },
  { id: "h_38", word: "すこし", romaji: "sukoshi", meaning: "Sedikit", mode: "hiragana" },
  { id: "h_39", word: "あそこ", romaji: "asoko", meaning: "Di sebelah sana", mode: "hiragana" },
  { id: "h_40", word: "すう", romaji: "suu", meaning: "Menghirup / Merokok", mode: "hiragana" },
  { id: "h_41", word: "さく", romaji: "saku", meaning: "Mekar", mode: "hiragana" },
  { id: "h_42", word: "おす", romaji: "osu", meaning: "Mendorong", mode: "hiragana" },
  { id: "h_43", word: "いた", romaji: "ita", meaning: "Papan", mode: "hiragana" },
  { id: "h_44", word: "うた", romaji: "uta", meaning: "Lagu", mode: "hiragana" },
  { id: "h_45", word: "おと", romaji: "oto", meaning: "Suara / Bunyi", mode: "hiragana" },
  { id: "h_46", word: "て", romaji: "te", meaning: "Tangan", mode: "hiragana" },
  { id: "h_47", word: "ちち", romaji: "chichi", meaning: "Ayah kandung", mode: "hiragana" },
  { id: "h_48", word: "くつ", romaji: "kutsu", meaning: "Sepatu", mode: "hiragana" },
  { id: "h_49", word: "つくえ", romaji: "tsukue", meaning: "Meja", mode: "hiragana" },
  { id: "h_50", word: "ちかてつ", romaji: "chikatetsu", meaning: "Kereta Bawah Tanah", mode: "hiragana" },
  { id: "h_51", word: "こと", romaji: "koto", meaning: "Hal / Urusan", mode: "hiragana" },
  { id: "h_52", word: "たかい", romaji: "takai", meaning: "Tinggi / Mahal", mode: "hiragana" },
  { id: "h_53", word: "あつい", romaji: "atsui", meaning: "Panas / Tebal", mode: "hiragana" },
  { id: "h_54", word: "いたい", romaji: "itai", meaning: "Sakit / Nyeri", mode: "hiragana" },
  { id: "h_55", word: "たつ", romaji: "tatsu", meaning: "Berdiri", mode: "hiragana" },
  { id: "h_56", word: "まつ", romaji: "matsu", meaning: "Menunggu", mode: "hiragana" },
  { id: "h_57", word: "した", romaji: "shita", meaning: "Bawah", mode: "hiragana" },
  { id: "h_58", word: "そと", romaji: "soto", meaning: "Luar", mode: "hiragana" },
  { id: "h_59", word: "ちいさい", romaji: "chiisai", meaning: "Kecil", mode: "hiragana" },
  { id: "h_60", word: "うつくしい", romaji: "utsukushii", meaning: "Indah / Cantik", mode: "hiragana" },
  { id: "h_61", word: "とき", romaji: "toki", meaning: "Waktu", mode: "hiragana" },
  { id: "h_62", word: "とけい", romaji: "tokei", meaning: "Jam tangan / Dinding", mode: "hiragana" },
  { id: "h_63", word: "いぬ", romaji: "inu", meaning: "Anjing", mode: "hiragana" },
  { id: "h_64", word: "ねこ", romaji: "neko", meaning: "Kucing", mode: "hiragana" },
  { id: "h_65", word: "くに", romaji: "kuni", meaning: "Negara", mode: "hiragana" },
  { id: "h_66", word: "なに", romaji: "nani", meaning: "Apa", mode: "hiragana" },
  { id: "h_67", word: "きのこ", romaji: "kinoko", meaning: "Jamur", mode: "hiragana" },
  { id: "h_68", word: "さかな", romaji: "sakana", meaning: "Ikan", mode: "hiragana" },
  { id: "h_69", word: "おかね", romaji: "okane", meaning: "Uang", mode: "hiragana" },
  { id: "h_70", word: "あなた", romaji: "anata", meaning: "Anda / Kamu", mode: "hiragana" },
  { id: "h_71", word: "あに", romaji: "ani", meaning: "Kakak laki-laki", mode: "hiragana" },
  { id: "h_72", word: "あね", romaji: "ane", meaning: "Kakak perempuan", mode: "hiragana" },
  { id: "h_73", word: "なつ", romaji: "natsu", meaning: "Musim Panas", mode: "hiragana" },
  { id: "h_74", word: "にく", romaji: "niku", meaning: "Daging", mode: "hiragana" },
  { id: "h_75", word: "たいせつ", romaji: "taisetsu", meaning: "Penting", mode: "hiragana" },
  { id: "h_76", word: "おとこのこ", romaji: "otokonoko", meaning: "Anak Laki-laki", mode: "hiragana" },
  { id: "h_77", word: "しぬ", romaji: "shinu", meaning: "Mati", mode: "hiragana" },
  { id: "h_78", word: "すな", romaji: "suna", meaning: "Pasir", mode: "hiragana" },
  { id: "h_79", word: "ひと", romaji: "hito", meaning: "Orang", mode: "hiragana" },
  { id: "h_80", word: "はな", romaji: "hana", meaning: "Bunga / Hidung", mode: "hiragana" },
  { id: "h_81", word: "はし", romaji: "hashi", meaning: "Jembatan / Sumpit", mode: "hiragana" },
  { id: "h_82", word: "ふね", romaji: "fune", meaning: "Perahu / Kapal", mode: "hiragana" },
  { id: "h_83", word: "ふゆ", romaji: "fuyu", meaning: "Musim Dingin", mode: "hiragana" },
  { id: "h_84", word: "ほし", romaji: "hoshi", meaning: "Bintang", mode: "hiragana" },
  { id: "h_85", word: "ほん", romaji: "hon", meaning: "Buku", mode: "hiragana" },
  { id: "h_86", word: "はこ", romaji: "hako", meaning: "Kotak", mode: "hiragana" },
  { id: "h_87", word: "へや", romaji: "heya", meaning: "Kamar / Ruangan", mode: "hiragana" },
  { id: "h_88", word: "ひかり", romaji: "hikari", meaning: "Cahaya", mode: "hiragana" },
  { id: "h_89", word: "みみ", romaji: "mimi", meaning: "Telinga", mode: "hiragana" },
  { id: "h_90", word: "め", romaji: "me", meaning: "Mata", mode: "hiragana" },
  { id: "h_91", word: "もり", romaji: "mori", meaning: "Hutan", mode: "hiragana" },
  { id: "h_92", word: "まち", romaji: "machi", meaning: "Kota", mode: "hiragana" },
  { id: "h_93", word: "みち", romaji: "michi", meaning: "Jalan", mode: "hiragana" },
  { id: "h_94", word: "みず", romaji: "mizu", meaning: "Air", mode: "hiragana" },
  { id: "h_95", word: "やま", romaji: "yama", meaning: "Gunung", mode: "hiragana" },
  { id: "h_96", word: "ゆき", romaji: "yuki", meaning: "Salju", mode: "hiragana" },
  { id: "h_97", word: "よる", romaji: "yoru", meaning: "Malam", mode: "hiragana" },
  { id: "h_98", word: "ゆめ", romaji: "yume", meaning: "Mimpi", mode: "hiragana" },
  { id: "h_99", word: "さくら", romaji: "sakura", meaning: "Bunga Sakura", mode: "hiragana" },
  { id: "h_100", word: "とり", romaji: "tori", meaning: "Burung", mode: "hiragana" },
  { id: "h_101", word: "そら", romaji: "sora", meaning: "Langit", mode: "hiragana" },
  { id: "h_102", word: "はる", romaji: "haru", meaning: "Musim Semi", mode: "hiragana" },
  { id: "h_103", word: "かわ", romaji: "kawa", meaning: "Sungai", mode: "hiragana" },
  { id: "h_104", word: "わたし", romaji: "watashi", meaning: "Saya", mode: "hiragana" },
  { id: "h_105", word: "くるま", romaji: "kuruma", meaning: "Mobil", mode: "hiragana" },
  { id: "h_106", word: "せんせい", romaji: "sensei", meaning: "Guru / Dokter", mode: "hiragana" },
  { id: "h_107", word: "がくせい", romaji: "gakusei", meaning: "Murid / Mahasiswa", mode: "hiragana" },
  { id: "h_108", word: "ともだち", romaji: "tomodachi", meaning: "Teman", mode: "hiragana" },
  { id: "h_109", word: "かぞく", romaji: "kazoku", meaning: "Keluarga", mode: "hiragana" },
  { id: "h_110", word: "にほん", romaji: "nihon", meaning: "Jepang", mode: "hiragana" },
  { id: "h_111", word: "ありがとう", romaji: "arigatou", meaning: "Terima kasih", mode: "hiragana" },
  { id: "h_112", word: "おはよう", romaji: "ohayou", meaning: "Selamat pagi", mode: "hiragana" },
  { id: "h_113", word: "こんばんは", romaji: "konbanwa", meaning: "Selamat malam", mode: "hiragana" },
  { id: "h_114", word: "さようなら", romaji: "sayounara", meaning: "Selamat tinggal", mode: "hiragana" },
  { id: "h_115", word: "きょう", romaji: "kyou", meaning: "Hari ini", mode: "hiragana" },
  { id: "h_116", word: "あした", romaji: "ashita", meaning: "Besok", mode: "hiragana" },
  { id: "h_117", word: "きのう", romaji: "kinou", meaning: "Kemarin", mode: "hiragana" },
  { id: "h_118", word: "まいあさ", romaji: "maiasa", meaning: "Setiap pagi", mode: "hiragana" },
  { id: "h_119", word: "まいばん", romaji: "maiban", meaning: "Setiap malam", mode: "hiragana" },
  { id: "h_120", word: "まいにち", romaji: "mainichi", meaning: "Setiap hari", mode: "hiragana" },
  { id: "h_121", word: "あめ", romaji: "ame", meaning: "Hujan / Permen", mode: "hiragana" },
  { id: "h_122", word: "おちゃ", romaji: "ocha", meaning: "Teh hijau", mode: "hiragana" },
  { id: "h_123", word: "みかん", romaji: "mikan", meaning: "Jeruk mandarin", mode: "hiragana" },
  { id: "h_124", word: "りんご", romaji: "ringo", meaning: "Apel", mode: "hiragana" },
  { id: "h_125", word: "たまご", romaji: "tamago", meaning: "Telur", mode: "hiragana" },
  { id: "h_126", word: "ごはん", romaji: "gohan", meaning: "Nasi / Makanan", mode: "hiragana" },
  { id: "h_127", word: "あさごはん", romaji: "asagohan", meaning: "Sarapan pagi", mode: "hiragana" },
  { id: "h_128", word: "ひるごはん", romaji: "hirugohan", meaning: "Makan siang", mode: "hiragana" },
  { id: "h_129", word: "ばんごはん", romaji: "bangohan", meaning: "Makan malam", mode: "hiragana" },
  { id: "h_130", word: "みせ", romaji: "mise", meaning: "Toko", mode: "hiragana" },
  { id: "h_131", word: "ぎんこう", romaji: "ginkou", meaning: "Bank", mode: "hiragana" },
  { id: "h_132", word: "びょういん", romaji: "byouin", meaning: "Rumah Sakit", mode: "hiragana" },
  { id: "h_133", word: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "Kantor Pos", mode: "hiragana" },
  { id: "h_134", word: "としょかん", romaji: "toshokan", meaning: "Perpustakaan", mode: "hiragana" },
  { id: "h_135", word: "えいがかん", romaji: "eigakan", meaning: "Bioskop", mode: "hiragana" },
  { id: "h_136", word: "がっこう", romaji: "gakkou", meaning: "Sekolah", mode: "hiragana" },
  { id: "h_137", word: "だいがく", romaji: "daigaku", meaning: "Universitas", mode: "hiragana" },
  { id: "h_138", word: "かいしゃ", romaji: "kaisha", meaning: "Perusahaan / Kantor", mode: "hiragana" },
  { id: "h_139", word: "ひこうき", romaji: "hikouki", meaning: "Pesawat Terbang", mode: "hiragana" },
  { id: "h_140", word: "じてんしゃ", romaji: "jitensha", meaning: "Sepeda", mode: "hiragana" },
  { id: "h_141", word: "しんかんせん", romaji: "shinkansen", meaning: "Kereta Cepat Shinkansen", mode: "hiragana" },
  { id: "h_142", word: "あるく", romaji: "aruku", meaning: "Berjalan kaki", mode: "hiragana" },
  { id: "h_143", word: "はしる", romaji: "hashiru", meaning: "Berlari", mode: "hiragana" },
  { id: "h_144", word: "およぐ", romaji: "oyogu", meaning: "Berenang", mode: "hiragana" },
  { id: "h_145", word: "のむ", romaji: "nomu", meaning: "Minum", mode: "hiragana" },
  { id: "h_146", word: "たべる", romaji: "taberu", meaning: "Makan", mode: "hiragana" },
  { id: "h_147", word: "みる", romaji: "miru", meaning: "Melihat / Menonton", mode: "hiragana" },
  { id: "h_148", word: "よむ", romaji: "yomu", meaning: "Membaca", mode: "hiragana" },
  { id: "h_149", word: "とる", romaji: "toru", meaning: "Mengambil / Memotret", mode: "hiragana" },
  { id: "h_150", word: "する", romaji: "suru", meaning: "Melakukan", mode: "hiragana" },
  { id: "h_151", word: "くる", romaji: "kuru", meaning: "Datang", mode: "hiragana" },
  { id: "h_152", word: "かえる", romaji: "kaeru", meaning: "Pulang / Kembali", mode: "hiragana" },
  { id: "h_153", word: "ねる", romaji: "neru", meaning: "Tidur", mode: "hiragana" },
  { id: "h_154", word: "おきる", romaji: "okiru", meaning: "Bangun tidur", mode: "hiragana" },
  { id: "h_155", word: "べんきょう", romaji: "benkyou", meaning: "Belajar", mode: "hiragana" },
  { id: "h_156", word: "しごと", romaji: "shigoto", meaning: "Pekerjaan", mode: "hiragana" },
  { id: "h_157", word: "りょこう", romaji: "ryokou", meaning: "Wisata / Traveling", mode: "hiragana" },
  { id: "h_158", word: "かいもの", romaji: "kaimono", meaning: "Belanja", mode: "hiragana" },
  { id: "h_159", word: "さんぽ", romaji: "sanpo", meaning: "Jalan-jalan santai", mode: "hiragana" },
  { id: "h_160", word: "うたう", romaji: "utau", meaning: "Bernyanyi", mode: "hiragana" },
  { id: "h_161", word: "あそぶ", romaji: "asobu", meaning: "Bermain", mode: "hiragana" },
  { id: "h_162", word: "はなす", romaji: "hanasu", meaning: "Berbicara", mode: "hiragana" },
  { id: "h_163", word: "わかる", romaji: "wakaru", meaning: "Mengerti / Paham", mode: "hiragana" },
  { id: "h_164", word: "しる", romaji: "shiru", meaning: "Tahu / Mengenal", mode: "hiragana" },
  { id: "h_165", word: "おもう", romaji: "omou", meaning: "Berpikir / Mengira", mode: "hiragana" },
  { id: "h_166", word: "よぶ", romaji: "yobu", meaning: "Memanggil", mode: "hiragana" },
  { id: "h_167", word: "おしえる", romaji: "oshieru", meaning: "Mengajar / Memberitahu", mode: "hiragana" },
  { id: "h_168", word: "ならう", romaji: "narau", meaning: "Belajar dari orang lain", mode: "hiragana" },
  { id: "h_169", word: "てつだう", romaji: "tetsudau", meaning: "Membantu", mode: "hiragana" },
  { id: "h_170", word: "あける", romaji: "akeru", meaning: "Membuka", mode: "hiragana" },
  { id: "h_171", word: "しめる", romaji: "shimeru", meaning: "Menutup", mode: "hiragana" },
  { id: "h_172", word: "つける", romaji: "tsukeru", meaning: "Menyalakan", mode: "hiragana" },
  { id: "h_173", word: "けす", romaji: "kesu", meaning: "Mematikan / Menghapus", mode: "hiragana" },
  { id: "h_174", word: "いれる", romaji: "ireru", meaning: "Memasukkan", mode: "hiragana" },
  { id: "h_175", word: "だす", romaji: "dasu", meaning: "Mengeluarkan / Menyerahkan", mode: "hiragana" },
  { id: "h_176", word: "もつ", romaji: "motsu", meaning: "Membawa / Memiliki", mode: "hiragana" },
  { id: "h_177", word: "すむ", romaji: "sumu", meaning: "Tinggal / Menetap", mode: "hiragana" },
  { id: "h_178", word: "すわる", romaji: "suwaru", meaning: "Duduk", mode: "hiragana" },
  { id: "h_179", word: "はいる", romaji: "hairu", meaning: "Masuk", mode: "hiragana" },
  { id: "h_180", word: "でる", romaji: "deru", meaning: "Keluar", mode: "hiragana" },
  { id: "h_181", word: "わたる", romaji: "wataru", meaning: "Menyeberang", mode: "hiragana" },
  { id: "h_182", word: "まがる", romaji: "magaru", meaning: "Berbelok", mode: "hiragana" },
  { id: "h_183", word: "とまる", romaji: "tomaru", meaning: "Berhenti / Menginap", mode: "hiragana" },
  { id: "h_184", word: "くもり", romaji: "kumori", meaning: "Berawan", mode: "hiragana" },
  { id: "h_185", word: "はれ", romaji: "hare", meaning: "Cerah", mode: "hiragana" },
  { id: "h_186", word: "かぜ", romaji: "kaze", meaning: "Angin / Flu", mode: "hiragana" },
  { id: "h_187", word: "おんがく", romaji: "ongaku", meaning: "Musik", mode: "hiragana" },
  { id: "h_188", word: "しゃしん", romaji: "shashin", meaning: "Foto", mode: "hiragana" },
  { id: "h_189", word: "てがみ", romaji: "tegami", meaning: "Surat", mode: "hiragana" },
  { id: "h_190", word: "きっぷ", romaji: "kippu", meaning: "Tiket", mode: "hiragana" },
  { id: "h_191", word: "さいふ", romaji: "saifu", meaning: "Dompet", mode: "hiragana" },
  { id: "h_192", word: "かばん", romaji: "kaban", meaning: "Tas", mode: "hiragana" },
  { id: "h_193", word: "ぼうし", romaji: "boushi", meaning: "Topi", mode: "hiragana" },
  { id: "h_194", word: "めがね", romaji: "megane", meaning: "Kacamata", mode: "hiragana" },
  { id: "h_195", word: "ふく", romaji: "fuku", meaning: "Pakaian / Baju", mode: "hiragana" },
  { id: "h_196", word: "くつした", romaji: "kutsushita", meaning: "Kaos Kaki", mode: "hiragana" },
  { id: "h_197", word: "かぎ", romaji: "kagi", meaning: "Kunci", mode: "hiragana" },
  { id: "h_198", word: "かみ", romaji: "kami", meaning: "Kertas / Rambut / Dewa", mode: "hiragana" },
  { id: "h_199", word: "てちょう", romaji: "techou", meaning: "Buku Saku / Agenda", mode: "hiragana" },
  { id: "h_200", word: "じしょ", romaji: "jisho", meaning: "Kamus", mode: "hiragana" },
  { id: "h_201", word: "ざっし", romaji: "zasshi", meaning: "Majalah", mode: "hiragana" },
  { id: "h_202", word: "しんぶん", romaji: "shinbun", meaning: "Koran", mode: "hiragana" },
  { id: "h_203", word: "えんぴつ", romaji: "enpitsu", meaning: "Pensil", mode: "hiragana" },
  { id: "h_204", word: "けしごむ", romaji: "keshigomu", meaning: "Penghapus Karet", mode: "hiragana" },
  { id: "h_205", word: "でんわ", romaji: "denwa", meaning: "Telepon", mode: "hiragana" },
  { id: "h_206", word: "まど", romaji: "mado", meaning: "Jendela", mode: "hiragana" },
  { id: "h_207", word: "だいどころ", romaji: "daidokoro", meaning: "Dapur", mode: "hiragana" },
  { id: "h_208", word: "おふろ", romaji: "ofuro", meaning: "Bak Mandi Jepang", mode: "hiragana" },
  { id: "h_209", word: "にわ", romaji: "niwa", meaning: "Taman / Halaman", mode: "hiragana" },
  { id: "h_210", word: "げんかん", romaji: "genkan", meaning: "Pintu Masuk Rumah", mode: "hiragana" },
  { id: "h_211", word: "かいだん", romaji: "kaidan", meaning: "Tangga", mode: "hiragana" },
  { id: "h_212", word: "ろうか", romaji: "rouka", meaning: "Koridor / Lorong", mode: "hiragana" },
  { id: "h_213", word: "たてもの", romaji: "tatemono", meaning: "Bangunan / Gedung", mode: "hiragana" },
  { id: "h_214", word: "こうえん", romaji: "kouen", meaning: "Taman Kota", mode: "hiragana" },
  { id: "h_215", word: "うみ", romaji: "umi", meaning: "Laut / Pantai", mode: "hiragana" },
  { id: "h_216", word: "しま", romaji: "shima", meaning: "Pulau", mode: "hiragana" },
  { id: "h_217", word: "つき", romaji: "tsuki", meaning: "Bulan", mode: "hiragana" },
  { id: "h_218", word: "たいよう", romaji: "taiyou", meaning: "Matahari", mode: "hiragana" },
  { id: "h_219", word: "ひる", romaji: "hiru", meaning: "Siang hari", mode: "hiragana" },
  { id: "h_220", word: "ゆうがた", romaji: "yuugata", meaning: "Sore hari", mode: "hiragana" },
  { id: "h_221", word: "いま", romaji: "ima", meaning: "Sekarang", mode: "hiragana" },
  { id: "h_222", word: "ごぜん", romaji: "gozen", meaning: "Pagi (A.M.)", mode: "hiragana" },
  { id: "h_223", word: "ごご", romaji: "gogo", meaning: "Sore / Malam (P.M.)", mode: "hiragana" },
  { id: "h_224", word: "なんじ", romaji: "nanji", meaning: "Jam berapa", mode: "hiragana" },
  { id: "h_225", word: "なんぷん", romaji: "nanpun", meaning: "Menit berapa", mode: "hiragana" },
  { id: "h_226", word: "あさって", romaji: "asatte", meaning: "Lusa", mode: "hiragana" },
  { id: "h_227", word: "おととい", romaji: "ototoi", meaning: "Kemarin lusa", mode: "hiragana" },
  { id: "h_228", word: "こんしゅう", romaji: "konshuu", meaning: "Minggu ini", mode: "hiragana" },
  { id: "h_229", word: "らいしゅう", romaji: "raishuu", meaning: "Minggu depan", mode: "hiragana" },
  { id: "h_230", word: "せんしゅう", romaji: "senshuu", meaning: "Minggu lalu", mode: "hiragana" },
  { id: "h_231", word: "こんげつ", romaji: "kongetsu", meaning: "Bulan ini", mode: "hiragana" },
  { id: "h_232", word: "らいげつ", romaji: "raigetsu", meaning: "Bulan depan", mode: "hiragana" },
  { id: "h_233", word: "せんげつ", romaji: "sengetsu", meaning: "Bulan lalu", mode: "hiragana" },
  { id: "h_234", word: "ことし", romaji: "kotoshi", meaning: "Tahun ini", mode: "hiragana" },
  { id: "h_235", word: "らいねん", romaji: "rainen", meaning: "Tahun depan", mode: "hiragana" },
  { id: "h_236", word: "きょねん", romaji: "kyonen", meaning: "Tahun lalu", mode: "hiragana" },
  { id: "h_237", word: "げつようび", romaji: "getsuyoubi", meaning: "Hari Senin", mode: "hiragana" },
  { id: "h_238", word: "かようび", romaji: "kayoubi", meaning: "Hari Selasa", mode: "hiragana" },
  { id: "h_239", word: "すいようび", romaji: "suiyoubi", meaning: "Hari Rabu", mode: "hiragana" },
  { id: "h_240", word: "もくようび", romaji: "mokuyoubi", meaning: "Hari Kamis", mode: "hiragana" },
  { id: "h_241", word: "きんようび", romaji: "kinyoubi", meaning: "Hari Jumat", mode: "hiragana" },
  { id: "h_242", word: "どようび", romaji: "doyoubi", meaning: "Hari Sabtu", mode: "hiragana" },
  { id: "h_243", word: "にちようび", romaji: "nichiyoubi", meaning: "Hari Minggu", mode: "hiragana" },
  { id: "h_244", word: "あたま", romaji: "atama", meaning: "Kepala", mode: "hiragana" },
  { id: "h_245", word: "くち", romaji: "kuchi", meaning: "Mulut", mode: "hiragana" },
  { id: "h_246", word: "からだ", romaji: "karada", meaning: "Tubuh / Badan", mode: "hiragana" },
  { id: "h_247", word: "おなか", romaji: "onaka", meaning: "Perut", mode: "hiragana" },
  { id: "h_248", word: "せなか", romaji: "senaka", meaning: "Punggung", mode: "hiragana" },
  { id: "h_249", word: "むね", romaji: "mune", meaning: "Dada", mode: "hiragana" },
  { id: "h_250", word: "のど", romaji: "nodo", meaning: "Tenggorokan", mode: "hiragana" },
  { id: "h_251", word: "おとうさん", romaji: "otousan", meaning: "Ayah (formal)", mode: "hiragana" },
  { id: "h_252", word: "おかあさん", romaji: "okaasan", meaning: "Ibu (formal)", mode: "hiragana" },
  { id: "h_253", word: "おにいさん", romaji: "oniisan", meaning: "Kakak laki-laki", mode: "hiragana" },
  { id: "h_254", word: "おねえさん", romaji: "oneesan", meaning: "Kakak perempuan", mode: "hiragana" },
  { id: "h_255", word: "おとうと", romaji: "otouto", meaning: "Adik laki-laki", mode: "hiragana" },
  { id: "h_256", word: "いもうと", romaji: "imouto", meaning: "Adik perempuan", mode: "hiragana" },
  { id: "h_257", word: "おっと", romaji: "otto", meaning: "Suami", mode: "hiragana" },
  { id: "h_258", word: "つま", romaji: "tsuma", meaning: "Istri", mode: "hiragana" },
  { id: "h_259", word: "おとこのひと", romaji: "otokonohito", meaning: "Laki-laki dewasa", mode: "hiragana" },
  { id: "h_260", word: "おんなのひと", romaji: "onnanohito", meaning: "Perempuan dewasa", mode: "hiragana" },
  { id: "h_261", word: "おんなのこ", romaji: "onnanoko", meaning: "Anak Perempuan", mode: "hiragana" },
  { id: "h_262", word: "あかちゃん", romaji: "akachan", meaning: "Bayi", mode: "hiragana" },
  { id: "h_263", word: "おとな", romaji: "otona", meaning: "Orang Dewasa", mode: "hiragana" },
  { id: "h_264", word: "せいと", romaji: "seito", meaning: "Murid sekolah", mode: "hiragana" },
  { id: "h_265", word: "りゅうがくせい", romaji: "ryuugakusei", meaning: "Mahasiswa Internasional", mode: "hiragana" },
  { id: "h_266", word: "いしゃ", romaji: "isha", meaning: "Dokter", mode: "hiragana" },
  { id: "h_267", word: "かんごし", romaji: "kangoshi", meaning: "Perawat", mode: "hiragana" },
  { id: "h_268", word: "けいさつかん", romaji: "keisatsukan", meaning: "Petugas Polisi", mode: "hiragana" },
  { id: "h_269", word: "てんいん", romaji: "ten'in", meaning: "Pegawai Toko", mode: "hiragana" },
  { id: "h_270", word: "ぎんこういん", romaji: "ginkouin", meaning: "Pegawai Bank", mode: "hiragana" },
  { id: "h_271", word: "かいしゃいん", romaji: "kaishain", meaning: "Karyawan Perusahaan", mode: "hiragana" },

  // ================= KATAKANA (GAIRAIGO LOANWORDS) =================
  { id: "k_0", word: "アイス", romaji: "aisu", meaning: "Es Krim", mode: "katakana" },
  { id: "k_1", word: "アイスクリーム", romaji: "aisukuriimu", meaning: "Es Krim", mode: "katakana" },
  { id: "k_2", word: "アイドル", romaji: "aidoru", meaning: "Idola / Artis Idol", mode: "katakana" },
  { id: "k_3", word: "アイデア", romaji: "aidea", meaning: "Ide / Gagasan", mode: "katakana" },
  { id: "k_4", word: "アニメ", romaji: "anime", meaning: "Animasi / Anime", mode: "katakana" },
  { id: "k_5", word: "アパート", romaji: "apaato", meaning: "Apartemen", mode: "katakana" },
  { id: "k_6", word: "アプリ", romaji: "apuri", meaning: "Aplikasi", mode: "katakana" },
  { id: "k_7", word: "アルバイト", romaji: "arubaito", meaning: "Kerja Paruh Waktu", mode: "katakana" },
  { id: "k_8", word: "アルバム", romaji: "arubamu", meaning: "Album Foto / Musik", mode: "katakana" },
  { id: "k_9", word: "インターネット", romaji: "intaanetto", meaning: "Internet", mode: "katakana" },
  { id: "k_10", word: "イラスト", romaji: "irasuto", meaning: "Ilustrasi / Gambar", mode: "katakana" },
  { id: "k_11", word: "エアコン", romaji: "eakon", meaning: "AC Pendingin Ruangan", mode: "katakana" },
  { id: "k_12", word: "エスカレーター", romaji: "esukareetaa", meaning: "Eskalator", mode: "katakana" },
  { id: "k_13", word: "エレベーター", romaji: "erebeetaa", meaning: "Lift / Elevator", mode: "katakana" },
  { id: "k_14", word: "エネルギー", romaji: "enerugii", meaning: "Energi", mode: "katakana" },
  { id: "k_15", word: "カーテン", romaji: "kaaten", meaning: "Tirai / Gorden", mode: "katakana" },
  { id: "k_16", word: "カード", romaji: "kaado", meaning: "Kartu Identitas / Kredit", mode: "katakana" },
  { id: "k_17", word: "カレー", romaji: "karee", meaning: "Nasi Kari", mode: "katakana" },
  { id: "k_18", word: "カメラ", romaji: "kamera", meaning: "Kamera", mode: "katakana" },
  { id: "k_19", word: "カップ", romaji: "kappu", meaning: "Cangkir", mode: "katakana" },
  { id: "k_20", word: "カレンダー", romaji: "karendaa", meaning: "Kalender", mode: "katakana" },
  { id: "k_21", word: "ギター", romaji: "gitaa", meaning: "Gitar", mode: "katakana" },
  { id: "k_22", word: "グラス", romaji: "gurasu", meaning: "Gelas Kaca", mode: "katakana" },
  { id: "k_23", word: "クラス", romaji: "kurasu", meaning: "Kelas / Tingkatan", mode: "katakana" },
  { id: "k_24", word: "クラブ", romaji: "kurabu", meaning: "Klub / Ekstrakurikuler", mode: "katakana" },
  { id: "k_25", word: "クリスマス", romaji: "kurisumasu", meaning: "Hari Natal", mode: "katakana" },
  { id: "k_26", word: "ケーキ", romaji: "keeki", meaning: "Kue Tart / Cake", mode: "katakana" },
  { id: "k_27", word: "ゲーム", romaji: "geemu", meaning: "Game / Permainan", mode: "katakana" },
  { id: "k_28", word: "コーヒー", romaji: "koohii", meaning: "Kopi", mode: "katakana" },
  { id: "k_29", word: "コート", romaji: "kooto", meaning: "Mantel / Jas Musim Dingin", mode: "katakana" },
  { id: "k_30", word: "コピー", romaji: "kopii", meaning: "Fotokopi / Salinan", mode: "katakana" },
  { id: "k_31", word: "コンサート", romaji: "konsaato", meaning: "Konser Musik", mode: "katakana" },
  { id: "k_32", word: "コンピューター", romaji: "konpyuutaa", meaning: "Komputer", mode: "katakana" },
  { id: "k_33", word: "コンビニ", romaji: "konbini", meaning: "Minimarket", mode: "katakana" },
  { id: "k_34", word: "サラダ", romaji: "sarada", meaning: "Salad Sayur", mode: "katakana" },
  { id: "k_35", word: "サンダル", romaji: "sandaru", meaning: "Sandal", mode: "katakana" },
  { id: "k_36", word: "サンドイッチ", romaji: "sandoicchi", meaning: "Roti Lapis / Sandwich", mode: "katakana" },
  { id: "k_37", word: "サービス", romaji: "saabisu", meaning: "Layanan / Servis", mode: "katakana" },
  { id: "k_38", word: "シャツ", romaji: "shatsu", meaning: "Kemeja / Kaos", mode: "katakana" },
  { id: "k_39", word: "シャワー", romaji: "shawaa", meaning: "Mandi Shower", mode: "katakana" },
  { id: "k_40", word: "ジュース", romaji: "juusu", meaning: "Jus Buah", mode: "katakana" },
  { id: "k_41", word: "スカート", romaji: "sukaato", meaning: "Rok", mode: "katakana" },
  { id: "k_42", word: "スキー", romaji: "sukii", meaning: "Olahraga Ski", mode: "katakana" },
  { id: "k_43", word: "スプーン", romaji: "supuun", meaning: "Sendok", mode: "katakana" },
  { id: "k_44", word: "スポーツ", romaji: "supootsu", meaning: "Olahraga", mode: "katakana" },
  { id: "k_45", word: "ズボン", romaji: "zubon", meaning: "Celana Panjang", mode: "katakana" },
  { id: "k_46", word: "スマホ", romaji: "sumaho", meaning: "Smartphone / HP", mode: "katakana" },
  { id: "k_47", word: "スーパー", romaji: "suupaa", meaning: "Supermarket", mode: "katakana" },
  { id: "k_48", word: "スーツ", romaji: "suutsu", meaning: "Setelan Jas", mode: "katakana" },
  { id: "k_49", word: "スーツケース", romaji: "suutsukeesu", meaning: "Koper Pakaian", mode: "katakana" },
  { id: "k_50", word: "ステレオ", romaji: "sutereo", meaning: "Sistem Audio Stereo", mode: "katakana" },
  { id: "k_51", word: "ストロー", romaji: "sutoroo", meaning: "Sedotan Minuman", mode: "katakana" },
  { id: "k_52", word: "セーター", romaji: "seetaa", meaning: "Baju Hangat Sweter", mode: "katakana" },
  { id: "k_53", word: "ソファ", romaji: "sofa", meaning: "Kursi Sofa", mode: "katakana" },
  { id: "k_54", word: "タクシー", romaji: "takushii", meaning: "Taksi", mode: "katakana" },
  { id: "k_55", word: "タオル", romaji: "taoru", meaning: "Handuk", mode: "katakana" },
  { id: "k_56", word: "タイプ", romaji: "taipu", meaning: "Tipe / Mengetik", mode: "katakana" },
  { id: "k_57", word: "チーズ", romaji: "chiizu", meaning: "Keju", mode: "katakana" },
  { id: "k_58", word: "チケット", romaji: "chiketto", meaning: "Tiket Masuk / Perjalanan", mode: "katakana" },
  { id: "k_59", word: "チョコレート", romaji: "chokoreeto", meaning: "Cokelat", mode: "katakana" },
  { id: "k_60", word: "テーブル", romaji: "teeburu", meaning: "Meja Makan", mode: "katakana" },
  { id: "k_61", word: "テープ", romaji: "teepu", meaning: "Pita / Selotip", mode: "katakana" },
  { id: "k_62", word: "テレビ", romaji: "terebi", meaning: "Televisi", mode: "katakana" },
  { id: "k_63", word: "テスト", romaji: "tesuto", meaning: "Ujian / Tes", mode: "katakana" },
  { id: "k_64", word: "テニス", romaji: "tenisu", meaning: "Olahraga Tenis", mode: "katakana" },
  { id: "k_65", word: "トイレ", romaji: "toire", meaning: "Toilet / Kamar Kecil", mode: "katakana" },
  { id: "k_66", word: "トースト", romaji: "toosuto", meaning: "Roti Panggang", mode: "katakana" },
  { id: "k_67", word: "トマト", romaji: "tomato", meaning: "Tomat", mode: "katakana" },
  { id: "k_68", word: "ドア", romaji: "doa", meaning: "Pintu", mode: "katakana" },
  { id: "k_69", word: "ドラマ", romaji: "dorama", meaning: "Serial Drama", mode: "katakana" },
  { id: "k_70", word: "ドレス", romaji: "doresu", meaning: "Gaun Wanita", mode: "katakana" },
  { id: "k_71", word: "ナイフ", romaji: "naifu", meaning: "Pisau Makan", mode: "katakana" },
  { id: "k_72", word: "ニュース", romaji: "nyuusu", meaning: "Berita Televisi", mode: "katakana" },
  { id: "k_73", word: "ネクタイ", romaji: "nekutai", meaning: "Dasi Pria", mode: "katakana" },
  { id: "k_74", word: "ノート", romaji: "nooto", meaning: "Buku Catatan", mode: "katakana" },
  { id: "k_75", word: "パーティー", romaji: "paatii", meaning: "Pesta", mode: "katakana" },
  { id: "k_76", word: "パソコン", romaji: "pasokon", meaning: "Laptop / Komputer PC", mode: "katakana" },
  { id: "k_77", word: "バス", romaji: "basu", meaning: "Bus Umum", mode: "katakana" },
  { id: "k_78", word: "バター", romaji: "bataa", meaning: "Mentega", mode: "katakana" },
  { id: "k_79", word: "バナナ", romaji: "banana", meaning: "Buah Pisang", mode: "katakana" },
  { id: "k_80", word: "パン", romaji: "pan", meaning: "Roti", mode: "katakana" },
  { id: "k_81", word: "ピアノ", romaji: "piano", meaning: "Piano", mode: "katakana" },
  { id: "k_82", word: "ビデオ", romaji: "bideo", meaning: "Rekaman Video", mode: "katakana" },
  { id: "k_83", word: "ビル", romaji: "biru", meaning: "Gedung Bertingkat", mode: "katakana" },
  { id: "k_84", word: "プール", romaji: "puuru", meaning: "Kolam Renang", mode: "katakana" },
  { id: "k_85", word: "フォーク", romaji: "fooku", meaning: "Garpu Makan", mode: "katakana" },
  { id: "k_86", word: "ベッド", romaji: "beddo", meaning: "Tempat Tidur / Kasur", mode: "katakana" },
  { id: "k_87", word: "ペット", romaji: "petto", meaning: "Hewan Peliharaan", mode: "katakana" },
  { id: "k_88", word: "ペン", romaji: "pen", meaning: "Pena Tinta", mode: "katakana" },
  { id: "k_89", word: "ボール", romaji: "booru", meaning: "Bola Olahraga", mode: "katakana" },
  { id: "k_90", word: "ボールペン", romaji: "boorupen", meaning: "Pena Bolpoin", mode: "katakana" },
  { id: "k_91", word: "ポケット", romaji: "poketto", meaning: "Saku Baju / Celana", mode: "katakana" },
  { id: "k_92", word: "ポスト", romaji: "posuto", meaning: "Kotak Surat Merah", mode: "katakana" },
  { id: "k_93", word: "ボタン", romaji: "botan", meaning: "Kancing Baju / Tombol", mode: "katakana" },
  { id: "k_94", word: "ホテル", romaji: "hoteru", meaning: "Hotel Penginapan", mode: "katakana" },
  { id: "k_95", word: "マフラー", romaji: "mafuraa", meaning: "Syal Leher", mode: "katakana" },
  { id: "k_96", word: "マンション", romaji: "manshon", meaning: "Apartemen Mewah", mode: "katakana" },
  { id: "k_97", word: "ミルク", romaji: "miruku", meaning: "Susu Sapi", mode: "katakana" },
  { id: "k_98", word: "メニュー", romaji: "menyuu", meaning: "Daftar Menu Makanan", mode: "katakana" },
  { id: "k_99", word: "メンバー", romaji: "membaa", meaning: "Anggota Tim", mode: "katakana" },
  { id: "k_100", word: "ラジオ", romaji: "rajio", meaning: "Radio Siaran", mode: "katakana" },
  { id: "k_101", word: "ランチ", romaji: "ranchi", meaning: "Makan Siang", mode: "katakana" },
  { id: "k_102", word: "レストラン", romaji: "resutoran", meaning: "Restoran", mode: "katakana" },
  { id: "k_103", word: "ワイシャツ", romaji: "waishatsu", meaning: "Kemeja Formal Putih", mode: "katakana" },
];
